In [1]:
#code to import a csv and convert it to a numpy array
#import the numpy library
import numpy as np
#open the file
raw_data = open("titanic.csv")
# load the CSV file as a numpy matrix
dataset = np.loadtxt(raw_data, delimiter=",")
#'shape' is the dimensions of the matrix
print(dataset.shape)
# separate the data from the target attributes
X = dataset[:,0:3]
y = dataset[:,3]
print(X)
print(y)

(2201, 4)
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 ..., 
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]]
[ 1.  1.  1. ...,  0.  0.  0.]


In [2]:
from sklearn.cross_validation import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import ensemble
from sklearn import neighbors
from sklearn import tree

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = .5)

tree_classifier = tree.DecisionTreeClassifier();
tree_classifier = tree_classifier.fit(X_train, y_train)
tree_predictions = tree_classifier.predict(X_test)

knn_classifier = neighbors.KNeighborsClassifier()
knn_classifier = knn_classifier.fit(X_train, y_train)
knn_predictions = knn_classifier.predict(X_test)

rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X_train, y_train)
rf_predictions = rf_classifier.predict(X_test)


print("tree: ", accuracy_score(tree_predictions, y_test))
print("KN: ", accuracy_score(knn_predictions, y_test))
print("RF: ", accuracy_score(rf_predictions, y_test))

tree:  0.779291553134
KN:  0.770208900999
RF:  0.779291553134


In [3]:
from sklearn.cross_validation import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import ensemble
from sklearn import neighbors
from sklearn import tree
import statistics as st
tree_classifier = tree.DecisionTreeClassifier();

for j in range(9):
    mean = []
    for i in range(10):#go to 10000
        X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = (j+1)/10)
        tree_classifier1 = tree_classifier.fit(X_train, y_train)
        tree_predictions = tree_classifier1.predict(X_test)
        mean.append(accuracy_score(tree_predictions, y_test))
    print((j+1)/10,":",st.mean(mean))

0.1 : 0.789862895928
0.2 : 0.789029024943
0.3 : 0.788152193646
0.4 : 0.78765584563
0.5 : 0.787202270663
0.6 : 0.787023769871
0.7 : 0.786302790396
0.8 : 0.784980408859
0.9 : 0.781184401817


In [7]:
from sklearn.cross_validation import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import ensemble
from sklearn import neighbors
from sklearn import tree
import statistics as st

tree_classifier = tree.DecisionTreeClassifier()
knn_classifier = neighbors.KNeighborsClassifier()
rf_classifier = ensemble.RandomForestClassifier()

DTlist = []
KNlist = []
RFlist = []

for i in range(10):#1000
    X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = .1)

    tree_classifier1 = tree_classifier.fit(X_train, y_train)
    tree_predictions = tree_classifier1.predict(X_test)
    DTlist.append(accuracy_score(tree_predictions, y_test))

    knn_classifier1 = knn_classifier.fit(X_train, y_train)
    knn_predictions = knn_classifier1.predict(X_test)
    KNlist.append(accuracy_score(knn_predictions, y_test))

    rf_classifier1 = rf_classifier.fit(X_train, y_train)
    rf_predictions = rf_classifier1.predict(X_test)
    RFlist.append(accuracy_score(rf_predictions, y_test))
    
means = {
    "DT" : st.mean(DTlist),
    "KN" : st.mean(KNlist),
    "RF" : st.mean(RFlist)
}
print("DT: ", means["DT"])
print("KN: ", means["KN"])
print("RF: ", means["RF"])
print(max(means, key=lambda key: means[key]))
#DT:  0.789914027149
#KN:  0.758669683258
#RF:  0.788918552036
#DT

DT:  0.789914027149
KN:  0.758669683258
RF:  0.788918552036
DT


In [22]:
from sklearn.cross_validation import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import ensemble
from sklearn import neighbors
from sklearn import tree
import statistics as st

tree_classifier = tree.DecisionTreeClassifier()
DTlist = []
a = [3, 1, 1]
b = [1, 1, 0]
c = [1, 0, 0]
aDeaths = []
bDeaths = []
cDeaths = []
for i in range(10000):
    X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = .1)

    tree_classifier1 = tree_classifier.fit(X_train, y_train)
    tree_predictions = tree_classifier1.predict(X_test)
    DTlist.append(accuracy_score(tree_predictions, y_test))
    
    aDeaths.append(float(tree_classifier1.predict([a])))
    bDeaths.append(float(tree_classifier1.predict([b])))
    cDeaths.append(float(tree_classifier1.predict([c])))
print("out of", len(aDeaths), "runs, person a. survived",sum(aDeaths),"times.")
print("out of", len(bDeaths), "runs, person a. survived",sum(bDeaths),"times.")
print("out of", len(cDeaths), "runs, person a. survived",sum(cDeaths),"times.")

out of 10000 runs, person a. survived 0.0 times.
out of 10000 runs, person a. survived 10000.0 times.
out of 10000 runs, person a. survived 10000.0 times.


In [48]:
from sklearn.cross_validation import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import ensemble
from sklearn import neighbors
from sklearn import tree
import statistics as st

tree_classifier = tree.DecisionTreeClassifier()

DTlist1 = []
DTlist2 = []
DTlist3 = []
X1 = np.delete(X, np.s_[0], 1)
X2 = np.delete(X, np.s_[1], 1)
X3 = np.delete(X, np.s_[2], 1)


for i in range(1000):#1000
    X_train, X_test, y_train, y_test = train_test_split(X1,y, test_size = .1)
    tree_classifier1 = tree_classifier.fit(X_train, y_train)
    tree_predictions = tree_classifier1.predict(X_test)
    DTlist1.append(accuracy_score(tree_predictions, y_test))
    
    X_train, X_test, y_train, y_test = train_test_split(X2,y, test_size = .1)
    tree_classifier1 = tree_classifier.fit(X_train, y_train)
    tree_predictions = tree_classifier1.predict(X_test)
    DTlist2.append(accuracy_score(tree_predictions, y_test))
    
    X_train, X_test, y_train, y_test = train_test_split(X3,y, test_size = .1)
    tree_classifier1 = tree_classifier.fit(X_train, y_train)
    tree_predictions = tree_classifier1.predict(X_test)
    DTlist3.append(accuracy_score(tree_predictions, y_test))
 
 
means = [st.mean(DTlist1),st.mean(DTlist2),st.mean(DTlist3)]
print("1", means[0])
print("2", means[1])
print("3", means[2])
max_value = max(means)
max_index = means.index(max_value)
print(max_index+1)

1 0.774787330317
2 0.782162895928
3 0.725022624434
2
